//! The single source of truth for API Tester's CSS theme contract.
//!
//! Parsing, editor intelligence, and documentation all consume these specs so
//! a property cannot be accepted by one surface and omitted from another.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum ThemePropertyKind {
    Name,
    Appearance,
    Color,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum ThemePropertyCategory {
    Metadata,
    Surfaces,
    Primary,
    Status,
    Semantic,
    Editor,
    Syntax,
}

impl ThemePropertyCategory {
    pub(crate) const fn label(self) -> &'static str {
        match self {
            Self::Metadata => "Theme metadata",
            Self::Surfaces => "Surfaces and text",
            Self::Primary => "Primary interaction",
            Self::Status => "Status colors",
            Self::Semantic => "Semantic palette",
            Self::Editor => "Code editor",
            Self::Syntax => "Syntax highlighting",
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct ThemePropertySpec {
    pub(crate) name: &'static str,
    pub(crate) kind: ThemePropertyKind,
    pub(crate) category: ThemePropertyCategory,
    pub(crate) required: bool,
    pub(crate) default_value: &'static str,
    pub(crate) documentation: &'static str,
}

const fn property(
    name: &'static str,
    kind: ThemePropertyKind,
    category: ThemePropertyCategory,
    required: bool,
    default_value: &'static str,
    documentation: &'static str,
) -> ThemePropertySpec {
    ThemePropertySpec {
        name,
        kind,
        category,
        required,
        default_value,
        documentation,
    }
}

pub(crate) const THEME_PROPERTIES: &[ThemePropertySpec] = &[
    property(
        "--api-theme-name",
        ThemePropertyKind::Name,
        ThemePropertyCategory::Metadata,
        true,
        "\"API Tester Material Dark\"",
        "Theme metadata used as the default library name when importing or saving CSS.",
    ),
    property(
        "--api-appearance",
        ThemePropertyKind::Appearance,
        ThemePropertyCategory::Metadata,
        true,
        "dark",
        "Selects the dark or light GPUI baseline used by components without an explicit token.",
    ),
    property(
        "--api-surface",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Surfaces,
        true,
        "#14121a",
        "Main window, workspace, tab, table, and accordion background.",
    ),
    property(
        "--api-surface-lowest",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Surfaces,
        true,
        "#0f0d14",
        "Deepest recessed surface, including editor backgrounds and dark overlays.",
    ),
    property(
        "--api-surface-low",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Surfaces,
        true,
        "#1c1a22",
        "Navigation rails, sidebars, group boxes, and low-elevation panels.",
    ),
    property(
        "--api-surface-container",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Surfaces,
        true,
        "#201e26",
        "Nested containers, popovers, and the default active editor line.",
    ),
    property(
        "--api-surface-high",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Surfaces,
        true,
        "#2b2931",
        "Hover surfaces, muted controls, progress tracks, and scrollbar thumbs.",
    ),
    property(
        "--api-surface-highest",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Surfaces,
        true,
        "#36343c",
        "Strong hover and elevated secondary-control surfaces.",
    ),
    property(
        "--api-foreground",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Surfaces,
        true,
        "#e6e0eb",
        "Primary application text and the default editor foreground.",
    ),
    property(
        "--api-muted-foreground",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Surfaces,
        true,
        "#cac4d0",
        "Secondary labels, placeholders, inactive tabs, and subdued metadata.",
    ),
    property(
        "--api-outline",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Surfaces,
        true,
        "#49454f",
        "Borders, dividers, input outlines, table rows, and the window outline.",
    ),
    property(
        "--api-primary",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Primary,
        true,
        "#e9ddff",
        "Primary buttons, active labels, links, and the syntax-keyword fallback.",
    ),
    property(
        "--api-primary-hover",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Primary,
        true,
        "#d0bcff",
        "Hovered primary controls, caret, active line numbers, and property syntax.",
    ),
    property(
        "--api-primary-active",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Primary,
        true,
        "#b9a6ed",
        "Pressed primary controls and active links.",
    ),
    property(
        "--api-primary-foreground",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Primary,
        true,
        "#37265e",
        "Text and icons displayed on a primary-colored surface.",
    ),
    property(
        "--api-selection",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Primary,
        true,
        "#4a4359",
        "Text selection, selected rows, active sidebar entries, and drop targets.",
    ),
    property(
        "--api-secondary-active",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Primary,
        false,
        "#5a526a",
        "Pressed secondary controls; falls back to the selection color when omitted.",
    ),
    property(
        "--api-secondary-foreground",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Primary,
        false,
        "#e9def9",
        "Text on secondary controls; falls back to the main foreground when omitted.",
    ),
    property(
        "--api-danger",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Status,
        true,
        "#8c1d18",
        "Destructive actions, error badges, and danger status.",
    ),
    property(
        "--api-danger-hover",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Status,
        false,
        "#a52a24",
        "Hovered destructive controls; falls back to danger when omitted.",
    ),
    property(
        "--api-danger-active",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Status,
        false,
        "#71120e",
        "Pressed destructive controls; falls back to danger when omitted.",
    ),
    property(
        "--api-danger-foreground",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Status,
        true,
        "#ffdad6",
        "Text and icons placed on danger surfaces.",
    ),
    property(
        "--api-warning",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Status,
        true,
        "#f4d06f",
        "Warnings, modified-state indicators, and caution status.",
    ),
    property(
        "--api-warning-hover",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Status,
        false,
        "#ffdc82",
        "Hovered warning controls; falls back to warning when omitted.",
    ),
    property(
        "--api-warning-active",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Status,
        false,
        "#d7b34f",
        "Pressed warning controls; falls back to warning when omitted.",
    ),
    property(
        "--api-warning-foreground",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Status,
        true,
        "#332b00",
        "Text and icons placed on warning surfaces.",
    ),
    property(
        "--api-success",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Status,
        true,
        "#2f6f44",
        "Successful requests, positive status, and enabled confirmations.",
    ),
    property(
        "--api-success-hover",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Status,
        false,
        "#3d8253",
        "Hovered success controls; falls back to success when omitted.",
    ),
    property(
        "--api-success-active",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Status,
        false,
        "#245c36",
        "Pressed success controls; falls back to success when omitted.",
    ),
    property(
        "--api-success-foreground",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Status,
        true,
        "#d0f8d8",
        "Text and icons placed on success surfaces.",
    ),
    property(
        "--api-info",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Status,
        true,
        "#385f8e",
        "Informational notices, links, and neutral status feedback.",
    ),
    property(
        "--api-info-hover",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Status,
        false,
        "#4771a4",
        "Hovered informational controls; falls back to info when omitted.",
    ),
    property(
        "--api-info-active",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Status,
        false,
        "#2c4d77",
        "Pressed informational controls; falls back to info when omitted.",
    ),
    property(
        "--api-info-foreground",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Status,
        true,
        "#d7e9ff",
        "Text and icons placed on informational surfaces.",
    ),
    property(
        "--api-red",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Semantic,
        true,
        "#ffb4ab",
        "Semantic red used by HTTP methods, charts, booleans, and bearish status.",
    ),
    property(
        "--api-red-light",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Semantic,
        false,
        "#ffdad6",
        "Lighter semantic red used where a softer red accent is needed.",
    ),
    property(
        "--api-green",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Semantic,
        true,
        "#4ade80",
        "Semantic green used by HTTP methods, charts, and bullish status.",
    ),
    property(
        "--api-green-light",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Semantic,
        false,
        "#b8f5c8",
        "Lighter semantic green accent.",
    ),
    property(
        "--api-blue",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Semantic,
        true,
        "#93c5fd",
        "Semantic blue used by HTTP methods, charts, and informational accents.",
    ),
    property(
        "--api-blue-light",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Semantic,
        false,
        "#d7e9ff",
        "Lighter semantic blue accent.",
    ),
    property(
        "--api-yellow",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Semantic,
        true,
        "var(--api-warning)",
        "Semantic yellow used by HTTP methods and charts.",
    ),
    property(
        "--api-yellow-light",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Semantic,
        false,
        "#ffecb3",
        "Lighter semantic yellow accent.",
    ),
    property(
        "--api-magenta",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Semantic,
        true,
        "#f0abfc",
        "Semantic magenta used by HTTP methods and charts.",
    ),
    property(
        "--api-magenta-light",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Semantic,
        false,
        "#f7d5ff",
        "Lighter semantic magenta accent.",
    ),
    property(
        "--api-cyan",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Semantic,
        true,
        "#67e8f9",
        "Semantic cyan used by HTTP methods and charts.",
    ),
    property(
        "--api-cyan-light",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Semantic,
        false,
        "#c9f8ff",
        "Lighter semantic cyan accent.",
    ),
    property(
        "--api-editor-background",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Editor,
        false,
        "var(--api-surface-lowest)",
        "Code editor canvas; falls back to the lowest surface.",
    ),
    property(
        "--api-editor-foreground",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Editor,
        false,
        "var(--api-foreground)",
        "Default code editor text; falls back to the main foreground.",
    ),
    property(
        "--api-editor-active-line",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Editor,
        false,
        "var(--api-surface-container)",
        "Background of the line containing the caret.",
    ),
    property(
        "--api-editor-line-number",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Editor,
        false,
        "#948f9a",
        "Inactive code editor line numbers.",
    ),
    property(
        "--api-editor-active-line-number",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Editor,
        false,
        "var(--api-primary-hover)",
        "Line number for the line containing the caret.",
    ),
    property(
        "--api-syntax-property",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Syntax,
        false,
        "var(--api-primary-hover)",
        "Object keys, CSS properties, and similar property-name captures.",
    ),
    property(
        "--api-syntax-string",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Syntax,
        false,
        "#ffd9e3",
        "String literals in request bodies and scripts.",
    ),
    property(
        "--api-syntax-number",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Syntax,
        false,
        "#efb8c8",
        "Numeric literals.",
    ),
    property(
        "--api-syntax-boolean",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Syntax,
        false,
        "var(--api-red)",
        "Boolean and null-like literals.",
    ),
    property(
        "--api-syntax-keyword",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Syntax,
        false,
        "var(--api-primary)",
        "Language keywords such as const, if, and return.",
    ),
    property(
        "--api-syntax-comment",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Syntax,
        false,
        "#948f9a",
        "Source-code comments.",
    ),
    property(
        "--api-syntax-punctuation",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Syntax,
        false,
        "var(--api-muted-foreground)",
        "Braces, commas, operators, and other punctuation.",
    ),
    property(
        "--api-syntax-variable",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Syntax,
        false,
        "var(--api-foreground)",
        "Variables and identifiers without a more specific capture.",
    ),
    property(
        "--api-syntax-type",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Syntax,
        false,
        "#ccc2dc",
        "Type names and type annotations.",
    ),
    property(
        "--api-syntax-function",
        ThemePropertyKind::Color,
        ThemePropertyCategory::Syntax,
        false,
        "var(--api-primary)",
        "Function names and calls.",
    ),
];

pub(crate) fn theme_property(name: &str) -> Option<&'static ThemePropertySpec> {
    THEME_PROPERTIES
        .iter()
        .find(|property| property.name == name)
}
