[package]
name = "resolved-updater"
version = "0.0.0"
edition = "2024"
publish = false
license = "Apache-2.0"

[workspace]
resolver = "3"

[dependencies]
serde_json = "=1.0.151"
resolved-release = { path = "../../crates/resolved-release" }
tokio = { version = "=1.53.1", features = ["rt", "time", "sync", "macros", "io-util", "fs", "process"] }
sha2 = "=0.10.9"
tempfile = "=3.27.0"
libc = "=0.2.189"
