name: Nightly builds
on:
  schedule:
    - cron: '23 2 * * *'
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  group: nightly-builds
  cancel-in-progress: false
jobs:
  build:
    uses: ./.github/workflows/build-release.yml
    with:
      channel: nightly
